### ISSUE TITLE
Node 14 version break

### ISSUE THREAD

**Issue by TeodorC95** [winstonjs/triple-beam#10]
I'm using Winstonjs which requires triple-beam as a dependency. Since I'm using node 14.x.x, the build now doesn't work. This seems to be a breaking change in the minor release of triple-beam. I'm aware that node 14 is eol, is this intended?

**Comment by MOL0ToK** [comment]
+

**Comment by akccakcctw** [comment]
same here 🤚🏼

**Comment by stasiukanya** [comment]
Same ++

**Comment by danez** [comment]
same here, please revert 1.4.0 and release 2.0

**Comment by cihanselim** [comment]
as a quick solution I downgraded newrelic to 8.0.0 for a short time. please revert the last change as mentioned above :|

**Comment by JandenMa** [comment]
Same here, but I don't use this package directly, I don't know which package is depending on it. Hmm when I upgraded my docker image to Node 16, it broke other deployments. That's not a good experience.

**Comment by christopher-watanabe-snkeos** [comment]
Same! 😭

**Comment by danez** [comment]
@indexzero @DABH

**Comment by foolzhang** [comment]
+1

**Comment by akshaynykaa** [comment]
+1

**Comment by AntoineTohan** [comment]
+1

**Comment by christopher-watanabe-snkeos** [comment]
For a quick fix, one can use "resolutions" if using yarn package manager. If using npm, there's apparently an overrides field, but I'm not so familiar with that. 

For reference https://stackoverflow.com/questions/52416312/npm-equivalent-of-yarn-resolutions. 

I was able to force my components to use v1.3.0 and my deployments work again.

**Comment by DABH** [comment]
Node 14 is EOL'd, and the Winston team only commits to supporting supported Node versions.  The recommendation would be to use package pinning, as suggested in the comment above, which should be a quick resolution for those of you still using unsupported Node versions (though note: there are serious security concerns with using EOL'd Node versions - you should really try to update!).

That being said, I think this is just a change in package.json, and I'm not aware with any failures on Node 14 (though if there were, we would not provide support), so I'm okay with tweaking the engines line and pushing a patch release.

**Comment by DABH** [comment]
Published as `v1.4.1`

**Comment by Speuta** [comment]
@DABH Thank you for the fix ! 🚀 

Please note that this can break some production CI, it's not a problem to upgrade Node version compatibility, but in this case please make a major version of your package ;)

**Comment by JandenMa** [comment]
As @danez and @Speuta  said, I agree that you should revert 1.4.x and release a new major version. @DABH

**Comment by JandenMa** [comment]
Thx for your fix! As @danez and @Speuta  said, I think you should revert 1.4.x and release a new major version. @DABH

**Comment by DABH** [comment]
@JandenMa Given we "restored compatibility" with Node 14 in 1.4.1, I don't see any reason to revert or do any further releases, unless people inform me that there are further issues.  Glad that things are working for you though!

**Comment by JandenMa** [comment]
@DABH Well I mean if you wanna stop supporting an EOL Node version, it would be safer to release a brand new major version. BTW for me, I think just bcoz some deps of serverless are depending on your package that broke the CI deployment, half a day lol. I am in China so you know during my working time, drove me crazy haha but it is fine I found a magic way to skip it. Anyway, thanks for your timely help.

**Comment by samueelM** [comment]
I'm from Brasil and this change  broke our CI as well. You really had should turn up your major version. It was really stressed and our team lost a lot of time to figure out what happen. So that change can cause a lot of problems in many projects.

**Comment by shammalie** [comment]
Can confirm issues with Node 6.11.3, this is a legacy app and can't upgrade node versions. Please recall version 1.4.x and release under major version 2.0.0.
